### ISSUE TITLE
Contact form update

### ISSUE THREAD

**Issue by npokharel** [npokharel/activehands#3]
redesign of contact us and address
reference - necofoundation.org

**Comment by kishan1991** [comment]
In Contact Us :
What else should we Include in it ...
Name :
Email Id:
Mobile No:
Yeti matrai ki aru nee Dai

**Comment by npokharel** [comment]
For the time being please put this  much only. Also please see this page http://necofoundation.org/contact/ 

The client wants address in the side of the page.
